<a href="https://colab.research.google.com/github/LeeDongHyun1001/cheetsheet/blob/main/cheatsheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch란?

*  tensorflow는 연산 그래프를 먼저 만들고 실제 연산할 때 값을 전달하여 결과를 얻는'Define and Run'방식

*   파이토치는 그래프를 만들과 동시에 값이 할당되는 'Define by Run'방식

둘 다 해야하고 최근에 Jax도 등장함



In [ ]:
import numpy as np
import torch

# 영행렬
0으로 채워진 5x2 텐서(행렬)만들기

파이토치의 기본 데이터 타입은 32비트 부동소수점

In [ ]:
z = torch.zeros(5,3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [ ]:
print(torch.randn(10)) # 평균 0인 숫자 (10)개 만들기
print(torch.rand(5,3)) # 0~1 숫자로 5x3행렬
print(torch.randperm(10)) # 0~10까지 정수 무작위
print(torch.randint(low=0, high=10, size=(2,4)))
print(torch.empty((4,3))) # 4x3사이즈의 빈 텐서
print(torch.empty(4).size())
print(torch.eye(3)) # 대각선 1 나머지 0
print(torch.eye(5,3))

tensor([-0.4835,  0.6831, -0.0048,  1.7082,  1.1403, -1.2579,  0.2983, -1.0062,
         0.2334, -0.6137])
tensor([[0.3280, 0.5546, 0.6437],
        [0.6709, 0.2887, 0.3544],
        [0.3579, 0.3395, 0.1766],
        [0.2843, 0.3597, 0.7207],
        [0.3541, 0.9756, 0.1458]])
tensor([2, 9, 3, 0, 7, 6, 4, 8, 5, 1])
tensor([[3, 5, 3, 8],
        [1, 8, 6, 9]])
tensor([[-2.1356e-30,  3.3186e-41, -2.4868e-30],
        [ 3.3186e-41,  7.2708e+31,  5.0778e+31],
        [ 3.2608e-12,  1.7728e+28,  7.0367e+22],
        [ 2.1715e-18,  1.0871e-05,  1.6502e-07]])
torch.Size([4])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])


# 1로 꽉찬 행렬과 dtype
ones((행렬), dtype=torch.타입지정)

In [ ]:
i = torch.ones((5,3), dtype=torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


seed를 통해 원하는 무작위값을 유도할 수 있음

In [ ]:
torch.manual_seed(1729)
r=torch.rand(2,2)
print('seed : ', r)
print('no seed : ', torch.rand(2,2))
print('seed : ', r)

seed :  tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])
no seed :  tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])
seed :  tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


manual_seed만 지정하면 재현이 안됨 (변화가능)

#시드 고정 코드

In [ ]:
import random

random_seed = 1729
torch.manual_seed(random_seed)
torch.cuda.manual_seed(random_seed)
torch.backends.cudnn.deterministic=True
torch.backends.cudnn.benchmark=False
np.random.seed(random_seed)
random.seed(random_seed)

# 3차원 이상의 행렬을 만들고 크기 확인

In [ ]:
z = torch.zeros(5,3,4)
print(z.shape)
print(z.size())

torch.Size([5, 3, 4])
torch.Size([5, 3, 4])


# Type casting

In [ ]:
# 리스트를 텐서로 바꾸기
torch.tensor([[1.,-1.], [1.,-1.]])

tensor([[ 1., -1.],
        [ 1., -1.]])

In [ ]:
# 뒤에 dtype으로 변환가능
x = torch.tensor([[1, -1], [1, -1]], dtype = torch.float32)
print(x)

tensor([[ 1., -1.],
        [ 1., -1.]])


In [ ]:
# np도 tensor변환 가능
np_array = np.array([[1,2,3], [4,5,6]])
x = torch.tensor(np_array, dtype=torch.float32)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


# 대소 비교하기

In [ ]:
a = torch.tensor([[2,5], [4,3]])
b = torch.tensor([[2,8], [2,3]])

print(torch.ne(a,b)) # 같음 부정
print(torch.eq(a,b)) # 같음
print(torch.le(a,b)) # 작은거
print(torch.ge(a,b)) # 큰거

print(torch.equal(a,b)) # 전체값을 비교해서 True, False 둘 중 하나값만 리턴

tensor([[False,  True],
        [ True, False]])
tensor([[ True, False],
        [False,  True]])
tensor([[ True,  True],
        [False,  True]])
tensor([[ True, False],
        [ True,  True]])
False


일정 소수점 이하는 같다는 규칙 만들기

In [ ]:
print(torch.allclose(torch.tensor([10000., 1e-07]), torch.tensor([10000.1, 1e-08])))
print(torch.allclose(torch.tensor([10000., 1e-08]), torch.tensor([10000.1, 1e-09])))
print(torch.allclose(torch.tensor([1.0, float('nan')]), torch.tensor([1.0, float('nan')])))
print(torch.allclose(torch.tensor([1.0, float('nan')]), torch.tensor([1.0, float('nan')]), equal_nan=True))

False
True
False
True


# 복사하기 Copy Tensor


*   clone : 메모리를 새롭게 할당, 계산그래프에 계속 상주
*   detach: 메모리를 공유, 계산그래프에서 뺌, 단 storage를 공유하기에 detach로 생성한 Tensor가 변경되면 원본 Tensor도 똑같이 변환



In [ ]:
x = torch.rand(size=(3,3))
print(x)

y = x.clone().detach()
print(torch.equal(x,y))

y = x.detach().clone() # 이게 좀 더 효율적
print(torch.equal(x,y))

tensor([[0.0936, 0.0243, 0.7260],
        [0.1272, 0.2228, 0.9738],
        [0.6903, 0.8095, 0.8368]])
True
True


In [ ]:
# deepcopy를 쓸 수 있는데... 위 방법 추천

import copy
x=torch.ones(10,requires_grad=True)
x_deepcopy = copy.deepcopy(x)
print(x,'x')
print(x_deepcopy,'x_deepcopy')

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True) x
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True) x_deepcopy


# 값을 cuda로 보내는법

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# 만약 컴퓨터 환경에 cuda가 가능하면 cuda아니면 cpu
# 코랩에 cpu뜨면 런타임에서 런타임유형을 변경해줘야함
print(device)


cuda


In [ ]:
# cuda에서 고속으로 돌리는법 to(device)
x = torch.tensor([[1, -1], [1, -1]])
x.to(device, dtype=torch.float32)
# 데이터 타입 지정도 가능
print(x)
print(x[0][0].item())
# cuda로 바뀐 내용 값 접근

tensor([[ 1, -1],
        [ 1, -1]])
1


# shape, dtype, device

In [ ]:
tensor = torch.rand(3,4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)
print(tensor.ndim)

torch.Size([3, 4])
torch.float32
cpu
2


# torch.tensor 기능들


1.   new
2.   new_zeros
3.   new_ones
4.   new_full

기존 tensor성질이 같은 복사본을 만들기


In [ ]:
original_tensor = torch.tensor([[1,2], [3,4]]).to(device, dtype=torch.float32)
# 뒤에 .to(device, dtype=torch.float32)로 디바이스, 타입지정 가능

new1 = original_tensor.new(2,2)
new_z = original_tensor.new_zeros(2,2)
new_o = original_tensor.new_ones(2,2)
new_f = original_tensor.new_full((2,2), fill_value=7.0)
print(new1)
print(new_z)
print(new_o)
print(new_f)

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')
tensor([[0., 0.],
        [0., 0.]], device='cuda:0')
tensor([[1., 1.],
        [1., 1.]], device='cuda:0')
tensor([[7., 7.],
        [7., 7.]], device='cuda:0')


In [ ]:
print(torch.arange(5))
print(torch.arange(1,4))
print(torch.arange(1,4,0.2)) # 슬라이싱이랑 비슷함

print(torch.linspace(1,4,20)) # 1부터 4까지 20개로 자르기
print(torch.logspace(1,4,20)) # 1부터 4까지를 로그로 표현

tensor([0, 1, 2, 3, 4])
tensor([1, 2, 3])
tensor([1.0000, 1.2000, 1.4000, 1.6000, 1.8000, 2.0000, 2.2000, 2.4000, 2.6000,
        2.8000, 3.0000, 3.2000, 3.4000, 3.6000, 3.8000])
tensor([1.0000, 1.1579, 1.3158, 1.4737, 1.6316, 1.7895, 1.9474, 2.1053, 2.2632,
        2.4211, 2.5789, 2.7368, 2.8947, 3.0526, 3.2105, 3.3684, 3.5263, 3.6842,
        3.8421, 4.0000])
tensor([   10.0000,    14.3845,    20.6914,    29.7635,    42.8133,    61.5848,
           88.5867,   127.4275,   183.2981,   263.6651,   379.2690,   545.5594,
          784.7599,  1128.8379,  1623.7767,  2335.7214,  3359.8184,  4832.9302,
         6951.9277, 10000.0000])


torch.complex로 복소수 만들기 가능

# in_place = 뒤에 _가 붙은 경우
method 뒤에 _가 있응면 in_place=True 구조와 같은 (원본자체를 바꿈)

In [ ]:
a = torch.randn(4,4)
print(a)
a.fill_(3.5)
print(a)
a.add_(5)
print(a)

tensor([[-0.5544, -0.0641, -2.9160, -0.5640],
        [ 1.7505, -0.1477, -0.7784, -0.4494],
        [-0.3397,  0.1367, -0.7055, -0.1326],
        [ 0.3883, -0.2546, -1.0816, -1.9186]])
tensor([[3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000]])
tensor([[8.5000, 8.5000, 8.5000, 8.5000],
        [8.5000, 8.5000, 8.5000, 8.5000],
        [8.5000, 8.5000, 8.5000, 8.5000],
        [8.5000, 8.5000, 8.5000, 8.5000]])


contiguos -> 메모리 위치 바꾸기

reshape & view: 모양을 바꿈!


*   view : 원본 파일의 보는 방향만을 바꿈 (원본과 공유) 그리고 원본의 연속성을 보장
*   reshape : 연속성 / 원본 / 공유  보장하지 않음. 편안함




In [ ]:
print('-'*30)
x = torch.rand(2,3,4)
print(x)
y = x.view(2, -1) # 재정렬
print(y)

print('-'*30)
x = torch.rand(2, 3, 4)
x= x.reshape(2, -1)
print(x)

# view는 붙어있는 차원 떄어낼 때 쓰자. 원본을 보존! 보는 방향만 바꿈

------------------------------
tensor([[[0.7853, 0.0179, 0.2252, 0.6279],
         [0.0610, 0.8700, 0.2329, 0.2329],
         [0.0246, 0.5636, 0.2126, 0.1783]],

        [[0.6934, 0.2495, 0.6208, 0.1171],
         [0.8187, 0.7648, 0.8036, 0.8960],
         [0.8397, 0.1312, 0.6938, 0.9058]]])
tensor([[0.7853, 0.0179, 0.2252, 0.6279, 0.0610, 0.8700, 0.2329, 0.2329, 0.0246,
         0.5636, 0.2126, 0.1783],
        [0.6934, 0.2495, 0.6208, 0.1171, 0.8187, 0.7648, 0.8036, 0.8960, 0.8397,
         0.1312, 0.6938, 0.9058]])
------------------------------
tensor([[0.6982, 0.0480, 0.6937, 0.8728, 0.8081, 0.2710, 0.2847, 0.8252, 0.0810,
         0.8103, 0.7800, 0.6348],
        [0.6839, 0.2480, 0.5424, 0.0975, 0.1986, 0.6540, 0.4594, 0.4067, 0.0373,
         0.7956, 0.5167, 0.7404]])


In [ ]:
print(torch.zeros(3,2))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


#Squuze 와 unsqueeze : 필요없는 차원 넣고 빼기
- squeeze: 1인 차원을 없앰 반대는 늘리기

In [ ]:
x = torch.rand(3,1,4,5)
print(x)
x = x.squeeze() # [3,1,4,5] -> [3,4,5]
print(x)

# 중요!
# batch가 1인 경우 batch차원을 없애버리는 상황이 생기니 주의
# torch의 데이터는 batch * channel * h * w

x2 = torch.rand(1, 1, 20 ,128)
x2 = x2.squeeze(dim=1) #[1,1,20,128] -> [1,20,128] dim으로 차원 명시

tensor([[[[0.5329, 0.5135, 0.5428, 0.0301, 0.0614],
          [0.8203, 0.2945, 0.9374, 0.0337, 0.5176],
          [0.9069, 0.8457, 0.0866, 0.1962, 0.8290],
          [0.6929, 0.2342, 0.0054, 0.7663, 0.7962]]],


        [[[0.1695, 0.8858, 0.1450, 0.0632, 0.7355],
          [0.9406, 0.4272, 0.0349, 0.3174, 0.7431],
          [0.1082, 0.9552, 0.8298, 0.8335, 0.7731],
          [0.7202, 0.9141, 0.0873, 0.9999, 0.4017]]],


        [[[0.9400, 0.9235, 0.4577, 0.3097, 0.8111],
          [0.2804, 0.2439, 0.3658, 0.0621, 0.1499],
          [0.8971, 0.1043, 0.9591, 0.3843, 0.0286],
          [0.2378, 0.5869, 0.3084, 0.8953, 0.4429]]]])
tensor([[[0.5329, 0.5135, 0.5428, 0.0301, 0.0614],
         [0.8203, 0.2945, 0.9374, 0.0337, 0.5176],
         [0.9069, 0.8457, 0.0866, 0.1962, 0.8290],
         [0.6929, 0.2342, 0.0054, 0.7663, 0.7962]],

        [[0.1695, 0.8858, 0.1450, 0.0632, 0.7355],
         [0.9406, 0.4272, 0.0349, 0.3174, 0.7431],
         [0.1082, 0.9552, 0.8298, 0.8335, 0.7731],
      

In [ ]:
inputs = torch.rand(3, 100, 100)
print(inputs.unsqueeze(1).shape) # [3,100,100] -> [3,1,100,100]

torch.Size([3, 1, 100, 100])


# transpose & permute
- transpose() : 2개의 차원을 교환(swap)
- permute() : 모든 차원의 순서를 재배치

In [ ]:
x = torch.rand(3,3,3)
print(x)
y = x.transpose(0,2)  # 0 - 2 차원변경
print(y)
z = x.permute(2, 1, 0) # 0->2, 1->1, 2->0 으로 변경
print(z)
#permute(1,0,2).configuous() 조합을 많이 씀!
# transpose(0,2) = 병. 을 .갑
# permute(2,1,0) = 병, 을 ,갑

tensor([[[0.4942, 0.2569, 0.6219],
         [0.1360, 0.4766, 0.6073],
         [0.6636, 0.8423, 0.4944]],

        [[0.8676, 0.1202, 0.7852],
         [0.6362, 0.6366, 0.2035],
         [0.0965, 0.5505, 0.3267]],

        [[0.5237, 0.0627, 0.4160],
         [0.1569, 0.7420, 0.5694],
         [0.9318, 0.3625, 0.2231]]])
tensor([[[0.4942, 0.8676, 0.5237],
         [0.1360, 0.6362, 0.1569],
         [0.6636, 0.0965, 0.9318]],

        [[0.2569, 0.1202, 0.0627],
         [0.4766, 0.6366, 0.7420],
         [0.8423, 0.5505, 0.3625]],

        [[0.6219, 0.7852, 0.4160],
         [0.6073, 0.2035, 0.5694],
         [0.4944, 0.3267, 0.2231]]])
tensor([[[0.4942, 0.8676, 0.5237],
         [0.1360, 0.6362, 0.1569],
         [0.6636, 0.0965, 0.9318]],

        [[0.2569, 0.1202, 0.0627],
         [0.4766, 0.6366, 0.7420],
         [0.8423, 0.5505, 0.3625]],

        [[0.6219, 0.7852, 0.4160],
         [0.6073, 0.2035, 0.5694],
         [0.4944, 0.3267, 0.2231]]])


# 자주쓰는 함수들

In [ ]:
r = (torch.rand(2,2) - 0.5) * 2  # -1과 1사이의 값을 가진다
print(r)

#삼각함수 사용가능
print(torch.asin(r))

# 평균 및 표준쳔차 / 최댓값
print(torch.std_mean(r))
print(torch.max(r))

tensor([[-0.6208, -0.1549],
        [ 0.5931, -0.6849]])
tensor([[-0.6697, -0.1555],
        [ 0.6349, -0.7545]])
(tensor(0.5894), tensor(-0.2169))
tensor(0.5931)


In [ ]:
# 배열에서 최댓값 구하기
y = torch.randint(100, (4,3,2))
print(y)
print(y.amax())
print(y.amax(keepdim=True)) # 차원까지 알려줌
print(y.argmax(dim=0))
print(y.argwhere()) # 0이 아닌요소 체크

tensor([[[65, 94],
         [37, 63],
         [19,  9]],

        [[95, 19],
         [31, 37],
         [18, 86]],

        [[81, 26],
         [19, 76],
         [ 9, 80]],

        [[69, 36],
         [89, 20],
         [44, 40]]])
tensor(95)
tensor([[[95]]])
tensor([[1, 0],
        [3, 2],
        [3, 1]])
tensor([[0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 1],
        [0, 2, 0],
        [0, 2, 1],
        [1, 0, 0],
        [1, 0, 1],
        [1, 1, 0],
        [1, 1, 1],
        [1, 2, 0],
        [1, 2, 1],
        [2, 0, 0],
        [2, 0, 1],
        [2, 1, 0],
        [2, 1, 1],
        [2, 2, 0],
        [2, 2, 1],
        [3, 0, 0],
        [3, 0, 1],
        [3, 1, 0],
        [3, 1, 1],
        [3, 2, 0],
        [3, 2, 1]])
